version: 2

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -buildvcs=false
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
    binary: "{{ .ProjectName }}_v{{ .Version }}"
    ldflags:
      - -s -w -buildid= -X main.version={{ .Version }}

archives:
  - formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
  extra_files:
    - glob: ./terraform-registry-manifest.json
      name_template: "{{ .ProjectName }}_{{ .Version }}_manifest.json"

signs:
  - artifacts: checksum
    args:
      - --batch
      - --local-user
      - "{{ .Env.GPG_FINGERPRINT }}"
      - --output
      - ${signature}
      - --detach-sign
      - ${artifact}

release:
  draft: false
  prerelease: auto
  extra_files:
    - glob: ./terraform-registry-manifest.json
      name_template: "{{ .ProjectName }}_{{ .Version }}_manifest.json"

changelog:
  use: git
  sort: asc
